### PR TITLE
 fix for Suave >=2.2.0

### PR DESCRIPTION
**Pull request by Badmoonz**

### CODE REVIEW

**Comment by Badmoonz** [comment]
may be we should add here travis ci  too?

**Comment by ncthbrt** [comment]
Up to you. You should have commit access :)

**Comment by ncthbrt** [comment]
@Badmoonz I've created the [fable-websockets](https://github.com/fable-websockets/) github organization. I'm not in a position to be a good steward for this project and thus feel that if there is interest, I should step out the way as otherwise I'm just slowing things down.

**Comment by Badmoonz** [comment]
I think it will be better some day to join something like SAFE-contrib organisation to get more attention and support for projects.

@ncthbrt , is it ok to bind my travis and appveyor accounts to fable-websockets for CI?

**Comment by ncthbrt** [comment]
Of course.

**Pull request merged**
